name: Node CI Pipeline
on: [push, pull_request]
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      # installing Node
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          # this will use the latest Node 12 version
          node-version: 18.x
      # install dependencies using clean install to avoid package lock updates
      - run: npm install --package-lock-only
      - run: npm ci
      # build the project if necessary
      - run: npm run build --if-present
      # prettier and lint
      - run: npm run lint
      - run: npm run format
      # finally run the tests
      - run: npm run test